# pull official base image
FROM node:13.12.0-alpine
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --production
RUN npm install react-scripts@3.4.1 -g --silent
# add app
COPY . ./
ENV var ''
RUN sed -i "3s/.*/export const api_url = \"http:\/\/localhost:8000\" ;/" src/components/Constants.js
# RUN echo 
CMD ["npm", "start"]
